-- =====================================================================================
-- SKEMA PANGKALAN DATA UNTUK SISTEM AFFILIATE (FASA 2)
-- =====================================================================================
-- Arahan: Sila jalankan kod SQL ini di dalam Supabase SQL Editor anda.
-- Ia akan menyediakan semua jadual dan kolum yang diperlukan untuk Fasa 2.

-- -------------------------------------------------------------------------------------
-- LANGKAH 1: CIPTA JADUAL 'affiliates'
-- Jadual ini akan menyimpan maklumat setiap pengguna yang telah berjaya mendaftar sebagai agen.
-- -------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.affiliates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    affiliate_code TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.affiliates IS 'Menyimpan data agen affiliate yang berdaftar.';
COMMENT ON COLUMN public.affiliates.user_id IS 'Pautan kepada pengguna dalam jadual auth.users.';
COMMENT ON COLUMN public.affiliates.affiliate_code IS 'Kod unik yang digunakan dalam pautan rujukan (cth: RAKAN-ABC123).';

-- Aktifkan Row Level Security (RLS) untuk jadual 'affiliates'
ALTER TABLE public.affiliates ENABLE ROW LEVEL SECURITY;

-- Benarkan semua pengguna (termasuk yang tidak log masuk) untuk membaca data ini.
-- Ini berguna jika anda mahu mengesahkan kod affiliate secara publik.
CREATE POLICY "Allow public read access to affiliates"
ON public.affiliates FOR SELECT
USING (true);


-- -------------------------------------------------------------------------------------
-- LANGKAH 2: CIPTA JADUAL 'sales'
-- Jadual ini akan merekodkan setiap transaksi langganan yang disahkan
-- yang datangnya daripada rujukan affiliate.
-- -------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    purchaser_user_id UUID NOT NULL REFERENCES auth.users(id),
    affiliate_id BIGINT NOT NULL REFERENCES public.affiliates(id),
    sale_amount NUMERIC(10, 2) NOT NULL,
    commission_rate NUMERIC(4, 2) NOT NULL DEFAULT 0.10, -- Kadar komisyen 10% secara lalai
    commission_amount NUMERIC(10, 2) GENERATED ALWAYS AS (sale_amount * commission_rate) STORED, -- Dikira secara automatik
    payout_status TEXT NOT NULL DEFAULT 'unpaid' -- Status pembayaran komisyen: 'unpaid', 'paid'
);

COMMENT ON TABLE public.sales IS 'Merekodkan setiap jualan yang berjaya dari rujukan affiliate.';
COMMENT ON COLUMN public.sales.purchaser_user_id IS 'ID pengguna yang membuat langganan.';
COMMENT ON COLUMN public.sales.affiliate_id IS 'ID agen affiliate yang membuat rujukan.';
COMMENT ON COLUMN public.sales.sale_amount IS 'Jumlah harga langganan.';
COMMENT ON COLUMN public.sales.commission_amount IS 'Jumlah komisyen yang dikira secara automatik.';

-- Aktifkan Row Level Security (RLS) untuk jadual 'sales'
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;

-- Hanya benarkan admin untuk mengakses data jualan.
-- PENTING: Anda perlu mempunyai logik untuk menetapkan peranan 'admin'.
CREATE POLICY "Allow admin full access to sales"
ON public.sales FOR ALL
USING ( (SELECT role FROM public.users WHERE user_id = auth.uid()) = 'admin' );

-- Benarkan affiliate membaca data jualan mereka sendiri SAHAJA.
CREATE POLICY "Allow affiliate to read their own sales"
ON public.sales FOR SELECT
USING ( (SELECT id FROM public.affiliates WHERE user_id = auth.uid()) = affiliate_id );


-- -------------------------------------------------------------------------------------
-- LANGKAH 3: KEMAS KINI JADUAL 'users' SEDIA ADA
-- Menambah satu kolum baru untuk menyimpan kod affiliate yang merujuk pengguna tersebut.
-- -------------------------------------------------------------------------------------
-- Gunakan blok DO...END untuk menambah kolum hanya jika ia belum wujud.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='users' AND column_name='referred_by') THEN
        ALTER TABLE public.users ADD COLUMN referred_by TEXT;
        COMMENT ON COLUMN public.users.referred_by IS 'Menyimpan kod affiliate (cth: RAKAN-ABC123) yang merujuk pengguna ini.';
    END IF;
END $$;

-- =====================================================================================
-- SELESAI. Sila jalankan skrip ini di Supabase.
-- =====================================================================================
