-- =====================================================================================
-- SKEMA PANGKALAN DATA UNTUK SISTEM AFFILIATE (FASA 2) - VERSI DIBAIKI
-- =====================================================================================
-- Arahan: Sila jalankan kod SQL ini di dalam Supabase SQL Editor anda.
-- Ia akan menyediakan semua jadual dan kolum yang diperlukan untuk Fasa 2.

-- -------------------------------------------------------------------------------------
-- LANGKAH 1: CIPTA JADUAL 'affiliates'
-- -------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.affiliates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    affiliate_code TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.affiliates IS 'Menyimpan data agen affiliate yang berdaftar.';

-- Aktifkan Row Level Security (RLS) untuk jadual 'affiliates'
ALTER TABLE public.affiliates ENABLE ROW LEVEL SECURITY;

-- Padam polisi lama jika wujud, kemudian cipta semula
DROP POLICY IF EXISTS "Allow public read access to affiliates" ON public.affiliates;
CREATE POLICY "Allow public read access to affiliates"
ON public.affiliates FOR SELECT
USING (true);


-- -------------------------------------------------------------------------------------
-- LANGKAH 2: CIPTA JADUAL 'sales'
-- -------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    purchaser_user_id UUID NOT NULL REFERENCES auth.users(id),
    affiliate_id BIGINT NOT NULL REFERENCES public.affiliates(id),
    sale_amount NUMERIC(10, 2) NOT NULL,
    commission_rate NUMERIC(4, 2) NOT NULL DEFAULT 0.10,
    commission_amount NUMERIC(10, 2) GENERATED ALWAYS AS (sale_amount * commission_rate) STORED,
    payout_status TEXT NOT NULL DEFAULT 'unpaid'
);

COMMENT ON TABLE public.sales IS 'Merekodkan setiap jualan yang berjaya dari rujukan affiliate.';

-- Aktifkan Row Level Security (RLS) untuk jadual 'sales'
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;

-- Padam polisi lama jika wujud, kemudian cipta semula
DROP POLICY IF EXISTS "Allow admin full access to sales" ON public.sales;
CREATE POLICY "Allow admin full access to sales"
ON public.sales FOR ALL
USING ( (SELECT role FROM public.users WHERE user_id = auth.uid()) = 'admin' );

DROP POLICY IF EXISTS "Allow affiliate to read their own sales" ON public.sales;
CREATE POLICY "Allow affiliate to read their own sales"
ON public.sales FOR SELECT
USING ( (SELECT id FROM public.affiliates WHERE user_id = auth.uid()) = affiliate_id );


-- -------------------------------------------------------------------------------------
-- LANGKAH 3: KEMAS KINI JADUAL 'users' SEDIA ADA
-- -------------------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='users' AND column_name='referred_by') THEN
        ALTER TABLE public.users ADD COLUMN referred_by TEXT;
        COMMENT ON COLUMN public.users.referred_by IS 'Menyimpan kod affiliate (cth: RAKAN-ABC123) yang merujuk pengguna ini.';
    END IF;
END $$;

-- =====================================================================================
-- SELESAI. Sila jalankan skrip ini di Supabase.
-- =====================================================================================