-- FAIL INI SENGAJA DIKOSONGKAN.
-- Logik trigger di dalam fail ini didapati berkonflik dengan logik yang sama di dalam kod aplikasi (api/approve-payment.js).
-- Untuk mengelakkan data jualan direkodkan dua kali dan untuk menyatukan logik di satu tempat,
-- fungsi trigger ini dilumpuhkan. Semua logik jualan kini diuruskan oleh kod aplikasi.
-- Jangan gunakan semula skrip di dalam fail ini tanpa menyahaktifkan logik yang berkaitan dalam aplikasi.