-- KEMAS KINI SKEMA DATABASE - VERSI DIBAIKI
-- Tarikh: 16 Nov 2025
-- Penerangan: Menambah jadual 'payments' untuk merekod butiran bayaran pengguna.

-- 1. CIPTA JADUAL 'payments' JIKA IA BELUM WUJUD
-- Jadual ini akan menyimpan setiap percubaan bayaran yang dihantar oleh pengguna.
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    reference_no TEXT NOT NULL,
    payment_date DATE NOT NULL,
    payment_time TIME NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending', -- Status bayaran ini: 'pending', 'verified', 'rejected'
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    verified_by UUID, -- ID admin yang sahkan, boleh jadi null
    verified_at TIMESTAMPTZ -- Bila admin sahkan
);

-- Tambah komen untuk kejelasan
COMMENT ON TABLE public.payments IS 'Merekodkan butiran bukti bayaran yang dihantar oleh pengguna.';
COMMENT ON COLUMN public.payments.user_id IS 'Pautan kepada pengguna yang membuat bayaran.';
COMMENT ON COLUMN public.payments.status IS 'Status untuk rekod bayaran spesifik ini.';

-- 2. AKTIFKAN ROW LEVEL SECURITY (RLS)
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- 3. CIPTA POLISI RLS (PADAM JIKA SUDAH WUJUD)

-- Polisi 1: Benarkan pengguna memasukkan rekod bayaran untuk diri mereka sendiri.
DROP POLICY IF EXISTS "Users can insert their own payment proofs." ON public.payments;
CREATE POLICY "Users can insert their own payment proofs."
ON public.payments FOR INSERT
WITH CHECK ( auth.uid() = user_id );

-- Polisi 2: Benarkan pengguna membaca rekod bayaran mereka sendiri sahaja.
DROP POLICY IF EXISTS "Users can read their own payment proofs." ON public.payments;
CREATE POLICY "Users can read their own payment proofs."
ON public.payments FOR SELECT
USING ( auth.uid() = user_id );

-- Polisi 3: Benarkan admin mengakses semua data dalam jadual 'payments'.
DROP POLICY IF EXISTS "Admins have full access to payments." ON public.payments;
CREATE POLICY "Admins have full access to payments."
ON public.payments FOR ALL
USING ( (SELECT role FROM public.users WHERE user_id = auth.uid()) = 'admin' );

-- ARAHAN:
-- 1. Pergi ke dashboard Supabase projek anda.
-- 2. Pergi ke "SQL Editor".
-- 3. Salin dan tampal SEMUA kandungan fail ini ke dalam editor.
-- 4. Klik "RUN" untuk melaksanakan skrip. Ini akan mencipta jadual 'payments' dan polisinya.