-- KEMAS KINI SKEMA DATABASE - VERSI DIBAIKI
-- Tarikh: 16 Nov 2025
-- Penerangan: Menambah jadual 'payments' untuk merekod butiran bayaran pengguna.

-- 0. PEMBETULAN KOLUM (MIGRATION)
-- PENYELESAIAN KEKAL: Menggunakan Trigger dan bukan Generated Column.
-- Ini membolehkan operasi INSERT, SELECT, dan UPDATE berfungsi serentak tanpa ralat.
DO $$
BEGIN
    -- 1. Pastikan kolum utama 'reference_no' wujud.
    --    Jika 'reference_no' tiada tetapi 'reference_text' ada, rename ia ke 'reference_no'.
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'payments' AND column_name = 'reference_no') THEN
        IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'payments' AND column_name = 'reference_text') THEN
            ALTER TABLE public.payments RENAME COLUMN reference_text TO reference_no;
        END IF;
    END IF;

    -- 2. Buang kolum 'reference_text' jika ia wujud (sama ada generated atau tidak).
    --    Kita akan cipta semula sebagai kolum biasa untuk elak konflik 'Generated Column'.
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'payments' AND column_name = 'reference_text') THEN
        ALTER TABLE public.payments DROP COLUMN reference_text CASCADE;
    END IF;

    -- 3. Cipta semula 'reference_text' sebagai kolum BIASA.
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'payments' AND column_name = 'reference_text') THEN
        ALTER TABLE public.payments ADD COLUMN reference_text TEXT;
    END IF;
END $$ LANGUAGE plpgsql;

-- 4. Backfill data: Pastikan reference_text ada data dari reference_no
UPDATE public.payments SET reference_text = reference_no WHERE reference_text IS NULL;

-- 5. CIPTA FUNGSI TRIGGER
-- Fungsi ini akan menyalin reference_no ke reference_text secara automatik setiap kali data masuk/ubah.
CREATE OR REPLACE FUNCTION public.sync_payment_reference()
RETURNS TRIGGER AS $func$
BEGIN
    NEW.reference_text := NEW.reference_no;
    RETURN NEW;
END;
$func$ LANGUAGE plpgsql;

-- 6. PASANG TRIGGER
DROP TRIGGER IF EXISTS trigger_sync_payment_reference ON public.payments;
CREATE TRIGGER trigger_sync_payment_reference
BEFORE INSERT OR UPDATE ON public.payments
FOR EACH ROW
EXECUTE FUNCTION public.sync_payment_reference();

-- 1. CIPTA JADUAL 'payments' JIKA IA BELUM WUJUD
-- Jadual ini akan menyimpan setiap percubaan bayaran yang dihantar oleh pengguna.
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    reference_no TEXT NOT NULL,
    reference_text TEXT, -- Kolum biasa, diuruskan oleh Trigger
    payment_date DATE NOT NULL,
    payment_time TIME NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending', -- Status bayaran ini: 'pending', 'verified', 'rejected'
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    verified_by UUID, -- ID admin yang sahkan, boleh jadi null
    verified_at TIMESTAMPTZ -- Bila admin sahkan
);

-- Tambah komen untuk kejelasan
COMMENT ON TABLE public.payments IS 'Merekodkan butiran bukti bayaran yang dihantar oleh pengguna.';
COMMENT ON COLUMN public.payments.user_id IS 'Pautan kepada pengguna yang membuat bayaran.';
COMMENT ON COLUMN public.payments.status IS 'Status untuk rekod bayaran spesifik ini.';

-- 2. AKTIFKAN ROW LEVEL SECURITY (RLS)
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- 3. CIPTA POLISI RLS (PADAM JIKA SUDAH WUJUD)

-- Polisi 1: Benarkan pengguna memasukkan rekod bayaran untuk diri mereka sendiri.
DROP POLICY IF EXISTS "Users can insert their own payment proofs." ON public.payments;
CREATE POLICY "Users can insert their own payment proofs."
ON public.payments FOR INSERT
WITH CHECK ( auth.uid() = user_id );

-- Polisi 2: Benarkan pengguna membaca rekod bayaran mereka sendiri sahaja.
DROP POLICY IF EXISTS "Users can read their own payment proofs." ON public.payments;
CREATE POLICY "Users can read their own payment proofs."
ON public.payments FOR SELECT
USING ( auth.uid() = user_id );

-- Polisi 3: Benarkan admin mengakses semua data dalam jadual 'payments'.
DROP POLICY IF EXISTS "Admins have full access to payments." ON public.payments;
CREATE POLICY "Admins have full access to payments."
ON public.payments FOR ALL
USING ( (SELECT role FROM public.users WHERE user_id = auth.uid()) = 'admin' );

-- 4. BERIKAN KEBENARAN KEPADA PENGGUNA YANG DISAHKAN
-- Ini memastikan peranan 'authenticated' boleh melakukan operasi yang dibenarkan oleh polisi RLS.
GRANT SELECT, INSERT, UPDATE, DELETE ON public.payments TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE payments_id_seq TO authenticated;

-- 5. PAKSA PENYEGARAN SEMULA SKEMA (PENTING UNTUK SUPABASE)
-- Arahan ini memberitahu API (PostgREST) untuk memuat semula skema databasenya.
-- Ini menyelesaikan ralat "column not found" yang disebabkan oleh cache yang lapuk.
NOTIFY pgrst, 'reload schema';