-- FAIL INI TIDAK LAGI DIGUNAKAN DAN DIANGGAP LAPUK.
-- Tarikh Nyahaktif: 25 Dis 2025
-- Sebab: Fail ini mengandungi definisi skema yang bercanggah dengan `public/schema_update.sql`.
-- Untuk mengelakkan ralat berulang berkaitan jadual 'payments', sila gunakan `public/schema_update.sql`
-- sebagai satu-satunya sumber rujukan yang sah untuk skema jadual 'payments'.
-- JANGAN JALANKAN KANDUNGAN FAIL INI.