-- Skema untuk jadual 'payments'

-- 1. PADAM JADUAL LAMA (JIKA PERLU)
DROP TABLE IF EXISTS public.payments CASCADE;

-- 2. CIPTA JADUAL 'payments'
CREATE TABLE public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    reference_no TEXT,
    payment_date DATE,
    payment_time TIME,
    amount NUMERIC(10, 2),
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- 3. AKTIFKAN ROW LEVEL SECURITY (RLS)
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- 4. CIPTA POLISI RLS
-- Polisi 1: Benarkan pengguna melihat pembayaran mereka sendiri.
CREATE POLICY "Users can view their own payments."
ON public.payments FOR SELECT
USING ( auth.uid() = user_id );

-- Polisi 2: Benarkan admin mengakses semua data.
CREATE POLICY "Admins have full access to payments."
ON public.payments FOR ALL
USING ( (SELECT role FROM public.users WHERE user_id = auth.uid()) = 'admin' );

COMMENT ON TABLE public.payments IS 'Menyimpan rekod pembayaran yang dibuat oleh pengguna.';
