-- Fail ini menyediakan skema SQL yang betul untuk projek anda menggunakan Supabase (PostgreSQL).
-- Anda perlu menjalankan kod ini di Supabase SQL Editor untuk menyediakan atau mengemas kini jadual anda.

-- 1. PADAM JADUAL LAMA (JIKA PERLU)
-- Jika anda memulakan semula, anda boleh memadam jadual lama dahulu.
DROP TABLE IF EXISTS public.users CASCADE;

-- 2. CIPTA JADUAL 'users' YANG BARU
-- Jadual ini menyimpan maklumat profil pengguna yang dipautkan kepada jadual 'auth.users' Supabase.
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Kunci utama auto-increment untuk jadual ini.
    user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE, -- Pautan wajib ke jadual pengesahan. Jika pengguna Auth dipadam, profil ini juga akan dipadam.
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'user',
    subscription_plan TEXT,
    subscription_price NUMERIC(10, 2), -- Harga dengan 2 titik perpuluhan.
    subscription_end_date DATE,
    is_promo_user BOOLEAN DEFAULT FALSE,
    payment_status TEXT DEFAULT 'pending', -- Contoh: 'pending', 'paid', 'rejected'.
    payment_reference TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Tambah komen pada jadual dan kolum untuk kejelasan.
COMMENT ON TABLE public.users IS 'Menyimpan profil dan maklumat langganan untuk setiap pengguna.';
COMMENT ON COLUMN public.users.user_id IS 'Foreign key kepada jadual auth.users.';


-- 3. AKTIFKAN ROW LEVEL SECURITY (RLS)
-- Ini adalah langkah keselamatan yang SANGAT PENTING untuk melindungi data pengguna.
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;


-- 4. CIPTA POLISI RLS
-- Polisi ini mengawal siapa yang boleh mengakses atau mengubah data.

-- Polisi 1: Benarkan pengguna membaca profil mereka sendiri sahaja.
CREATE POLICY "Users can read their own profile."
ON public.users FOR SELECT
USING ( auth.uid() = user_id );

-- Polisi 2: Benarkan pengguna mengemas kini maklumat profil mereka sendiri.
CREATE POLICY "Users can update their own profile."
ON public.users FOR UPDATE
USING ( auth.uid() = user_id );

-- Polisi 3: Benarkan admin mengakses semua data dalam jadual 'users'.
-- PENTING: Pastikan anda mempunyai logik untuk menetapkan 'role' kepada 'admin' untuk pengguna tertentu.
CREATE POLICY "Admins have full access."
ON public.users FOR ALL
USING ( (SELECT role FROM public.users WHERE user_id = auth.uid()) = 'admin' );


-- ARAHAN SELEPAS INI:
-- 1. Pergi ke dashboard Supabase projek anda.
-- 2. Pergi ke "SQL Editor".
-- 3. Salin dan tampal SEMUA kandungan fail ini ke dalam editor.
-- 4. Klik "RUN" untuk melaksanakan skrip. Ini akan mencipta jadual dan polisi keselamatan anda.
-- 5. Selepas ini, anda boleh push kod anda ke Vercel. Pendaftaran sepatutnya sudah berjaya.